    @a8 = { :rank => "8", :file => "a", :tilecolor => "white", :piece => "r" }
    @b8 = { :rank => "8", :file => "b", :tilecolor => "black", :piece => "n" }
    @c8 = { :rank => "8", :file => "c", :tilecolor => "white", :piece => "b" }
    @d8 = { :rank => "8", :file => "d", :tilecolor => "black", :piece => "q" }
    @e8 = { :rank => "8", :file => "e", :tilecolor => "white", :piece => "k" }
    @f8 = { :rank => "8", :file => "f", :tilecolor => "black", :piece => "b" }
    @g8 = { :rank => "8", :file => "g", :tilecolor => "white", :piece => "n" }
    @h8 = { :rank => "8", :file => "h", :tilecolor => "black", :piece => "r" }
    @a7 = { :rank => "7", :file => "a", :tilecolor => "black", :piece => "p" }
    @b7 = { :rank => "7", :file => "b", :tilecolor => "white", :piece => "p" }
    @c7 = { :rank => "7", :file => "c", :tilecolor => "black", :piece => "p" }
    @d7 = { :rank => "7", :file => "d", :tilecolor => "white", :piece => "p" }
    @e7 = { :rank => "7", :file => "e", :tilecolor => "black", :piece => "p" }
    @f7 = { :rank => "7", :file => "f", :tilecolor => "white", :piece => "p" }
    @g7 = { :rank => "7", :file => "g", :tilecolor => "black", :piece => "p" }
    @h7 = { :rank => "7", :file => "h", :tilecolor => "white", :piece => "p" }
    @a6 = { :rank => "6", :file => "a", :tilecolor => "white", :piece => "_" }
    @b6 = { :rank => "6", :file => "b", :tilecolor => "black", :piece => "_" }
    @c6 = { :rank => "6", :file => "c", :tilecolor => "white", :piece => "_" }
    @d6 = { :rank => "6", :file => "d", :tilecolor => "black", :piece => "_" }
    @e6 = { :rank => "6", :file => "e", :tilecolor => "white", :piece => "_" }
    @f6 = { :rank => "6", :file => "f", :tilecolor => "black", :piece => "_" }
    @g6 = { :rank => "6", :file => "g", :tilecolor => "white", :piece => "_" }
    @h6 = { :rank => "6", :file => "h", :tilecolor => "black", :piece => "_" }
    @a5 = { :rank => "5", :file => "a", :tilecolor => "black", :piece => "_" }
    @b5 = { :rank => "5", :file => "b", :tilecolor => "white", :piece => "_" }
    @c5 = { :rank => "5", :file => "c", :tilecolor => "black", :piece => "_" }
    @d5 = { :rank => "5", :file => "d", :tilecolor => "white", :piece => "_" }
    @e5 = { :rank => "5", :file => "e", :tilecolor => "black", :piece => "_" }
    @f5 = { :rank => "5", :file => "f", :tilecolor => "white", :piece => "_" }
    @g5 = { :rank => "5", :file => "g", :tilecolor => "black", :piece => "_" }
    @h5 = { :rank => "5", :file => "h", :tilecolor => "white", :piece => "_" }
    @a4 = { :rank => "4", :file => "a", :tilecolor => "white", :piece => "_" }
    @b4 = { :rank => "4", :file => "b", :tilecolor => "black", :piece => "_" }
    @c4 = { :rank => "4", :file => "c", :tilecolor => "white", :piece => "_" }
    @d4 = { :rank => "4", :file => "d", :tilecolor => "black", :piece => "_" }
    @e4 = { :rank => "4", :file => "e", :tilecolor => "white", :piece => "_" }
    @f4 = { :rank => "4", :file => "f", :tilecolor => "black", :piece => "_" }
    @g4 = { :rank => "4", :file => "g", :tilecolor => "white", :piece => "_" }
    @h4 = { :rank => "4", :file => "h", :tilecolor => "black", :piece => "_" }
    @a3 = { :rank => "3", :file => "a", :tilecolor => "black", :piece => "_" }
    @b3 = { :rank => "3", :file => "b", :tilecolor => "white", :piece => "_" }
    @c3 = { :rank => "3", :file => "c", :tilecolor => "black", :piece => "_" }
    @d3 = { :rank => "3", :file => "d", :tilecolor => "white", :piece => "_" }
    @e3 = { :rank => "3", :file => "e", :tilecolor => "black", :piece => "_" }
    @f3 = { :rank => "3", :file => "f", :tilecolor => "white", :piece => "_" }
    @g3 = { :rank => "3", :file => "g", :tilecolor => "black", :piece => "_" }
    @h3 = { :rank => "3", :file => "h", :tilecolor => "white", :piece => "_" }
    @a2 = { :rank => "2", :file => "a", :tilecolor => "white", :piece => "P" }
    @b2 = { :rank => "2", :file => "b", :tilecolor => "black", :piece => "P" }
    @c2 = { :rank => "2", :file => "c", :tilecolor => "white", :piece => "P" }
    @d2 = { :rank => "2", :file => "d", :tilecolor => "black", :piece => "P" }
    @e2 = { :rank => "2", :file => "e", :tilecolor => "white", :piece => "P" }
    @f2 = { :rank => "2", :file => "f", :tilecolor => "black", :piece => "P" }
    @g2 = { :rank => "2", :file => "g", :tilecolor => "white", :piece => "P" }
    @h2 = { :rank => "2", :file => "h", :tilecolor => "black", :piece => "P" }
    @a1 = { :rank => "1", :file => "a", :tilecolor => "black", :piece => "R" }
    @b1 = { :rank => "1", :file => "b", :tilecolor => "white", :piece => "N" }
    @c1 = { :rank => "1", :file => "c", :tilecolor => "black", :piece => "B" }
    @d1 = { :rank => "1", :file => "d", :tilecolor => "white", :piece => "Q" }
    @e1 = { :rank => "1", :file => "e", :tilecolor => "black", :piece => "K" }
    @f1 = { :rank => "1", :file => "f", :tilecolor => "white", :piece => "B" }
    @g1 = { :rank => "1", :file => "g", :tilecolor => "black", :piece => "N" }
    @h1 = { :rank => "1", :file => "h", :tilecolor => "white", :piece => "R" }

    #an array of each square which allows us to loop through every hash and find the hash whose rank = x and file = y
@all_squares = [ @a8, @b8, @c8, @d8, @e8, @f8, @g8, @h8, @a7, @b7, @c7, @d7, @e7, @f7, @g7, @h7,
    			       @a6, @b6, @c6, @d6, @e6, @f6, @g6, @h6, @a5, @b5, @c5, @d5, @e5, @f5, @g5, @h5,
    			       @a4, @b4, @c4, @d4, @e4, @f4, @g4, @h4, @a3, @b3, @c3, @d3, @e3, @f3, @g3, @h3,
    			       @a2, @b2, @c2, @d2, @e2, @f2, @g2, @h2, @a1, @b1, @c1, @d1, @e1, @f1, @g1, @h1 ]